POST http://localhost:80/api/user_recipe_mapping/create
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwaXJhdGlvbiI6IjIwMjMtMDktMDYgMTc6MjM6MTQuMjM4NjkwIn0.wVpCjLBynN1nUCk5n9E8HlE79sTtlMSbIXcdN3rhcZQ

{
  "recipe_id": "9"
}

###
GET http://localhost:5000/api/user_recipe_mapping/1