POST http://localhost:5000/api/user_recipe_mapping/create
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwaXJhdGlvbiI6IjIwMjMtMDktMTEgMDY6NDE6MjguNTU4ODU0In0.GEU1F_WV8LbwldxuvBzmvaF0I31AZ9rk4j5qzDZKNm8

{
  "recipe_id": "9"
}

###
GET http://localhost:5000/api/user_recipe_mapping/41