version: "3.8"

services:
  dev_db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db_postgres
    # ports:
    #   - 127.0.0.1:9999:5432
    volumes:
      - dev_database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build:
      context: ../backend
      # dockerfile: Dockerfile.backend
    command: >
      sh -c "FLASK_ENV=development flask run --host=0.0.0.0 --port=5000"
    env_file:
      - ../backend/.env
    container_name: recipe-finder-backend
    ports:
      - 5000:5000
    depends_on:
      - dev_db

volumes:
  dev_database: