version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
    command: bash -c "npm run start:prod"
    container_name: recipe-finder-frontend
    env_file:
      - ../frontend/.env
      
  backend:
    build:
      context: ../backend
    command: gunicorn --bind backend:5000 app:app
    env_file:
      - ../backend/.env
    container_name: recipe-finder-backend
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db_postgres
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  reverse-proxy:
    image: nginx:1.25.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  database:
